export const  permissionList = {
      Recycle_bin : 1,

      Create_Role : 2,
      View_Rolelist : 3,
      View_Role : 4,
      Delete_Role : 5,
      Change_User_Role : 6,

      Create_Menu : 7,
      View_Menulist : 8,
      View_Menu : 9,
      Edit_Menu : 10,
      Delete_Menu : 11,
      Asign_Menu : 12,

      Staff_List : 13,
      Add_Staff : 14,
      Update_Staff : 15,
      View_Staff : 16,
      Delete_Staff : 17,
      Staff_Activate_Deactivate : 18,

      Assign_University : 20,

      EmployeeTypeList : 21,

      Counsultant_List : 101,
      Add_Consultant : 102,
      Update_Consultant : 103,
      View_Consultant : 104,
      Delete_Consultant : 105,
      Consultant_Activate_Deactivate : 106,

      Associate_List : 107,
      Add_Associate : 108,
      Edit_Associate : 109,
      View_Associate : 110,
      Delete_Associate : 111,

      Add_Student_Consultant : 112,
      Update_Student_Consultant : 113,
      Student_Consultant_List : 114,
      Delete_Student_Consultant : 115,
      View_Student_Consultant : 116,
   //student
      Student_List : 201,
      Add_Student : 202,
      Update_Student : 203,
      View_Student : 204,
      Delete_Student : 205,
   //student type
      Student_type_List : 211,
      Add_Student_type : 212,
      Update_Student_type : 213,
      View_Student_type : 214,
      Delete_Student_type : 215,
   //student contact info
      student_contact_List : 221,
      Add_student_contact : 222,
      Update_student_contact : 223,
      View_student_contact : 224,
      Delete_student_contact : 225,
   //student consent controller
      student_consent_List : 231,
      Add_student_consent : 232,
      Update_student_consent : 233,
      View_student_consent : 234,
      Delete_student_consent : 235,
   //reference type
      referencetype_List : 236,
      View_referencetype : 237,
   //reference
      reference_List : 241,
      Add_reference : 242,
      Update_reference : 243,
      View_reference : 244,
      Delete_reference : 245,
   //personalstatement
      personalstatement_List : 251,
      Add_personalstatement : 252,
      Update_personalstatement : 253,
      View_personalstatement : 254,
      Delete_personalstatement : 255,
   //otherinfo
      otherinfo_List : 261,
      Add_otherinfo : 262,
      Update_otherinfo : 263,
      View_otherinfo : 264,
      Delete_otherinfo : 265,
   //grescore
      grescore_List : 271,
      Add_grescore : 272,
      Update_grescore : 273,
      View_grescore : 274,
      Delete_grescore : 275,
   //gmatscore
      gmatscore_List : 281,
      Add_gmatscore : 282,
      Update_gmatscore : 283,
      View_gmatscore : 284,
      Delete_gmatscore : 285,
   //experience
      experience_List : 291,
      Add_experience : 292,
      Update_experience : 293,
      View_experience : 294,
      Delete_experience : 295,
   //Educationinfo
      Educationinfo_List : 301,
      Add_Educationinfo : 302,
      Update_Educationinfo : 303,
      View_Educationinfo : 304,
      Delete_Educationinfo : 305,
   //Applicationinfo
      Applicationinfo_List : 311,
      Add_Applicationinfo : 312,
      Update_Applicationinfo : 313,
      View_Applicationinfo : 314,
      Delete_Applicationinfo : 315,
   //Student Documents
      Student_Documents_List : 316,
      Add_Student_Documents : 317,
      Update_Student_Documents : 318,
      View_Student_Documents : 319,
      Delete_Student_Documents : 320,
   //Student Type Documents
      Student_Type_Documents_List : 321,
      Add_Student_Type_Documents : 322,
      Update_Student_Type_Documents : 323,
      View_Student_Type_Documents : 324,
      Delete_Student_Type_Documents : 325,
   //Wish List
      Wish_List_List : 326,
      Add_Wish_List : 327,
      Update_Wish_List : 328,
      View_Wish_List : 329,
      Delete_Wish_List : 330,
   //Student Upload document
      Student_Upload_Document_List : 331,
      Add_Student_Upload_Document : 332,
      Update_Student_Upload_Document : 333,
      View_Student_Upload_Document : 334,
      Delete_Student_Upload_Document : 335,
   //Student document level
      Student_Document_Level_List : 336,
      Add_Student_Document_Level : 337,
      Update_Student_Document_Level : 338,
      View_Student_Document_Level : 339,
      Delete_Student_Document_Level : 340,

   //branch
      Branch_List : 401,
      Add_Branch : 402,
      Update_Branch : 403,
      View_Branch : 404,
      Delete_Branch : 405,
   //branchEmployee
      Branch_Employee_List : 411,
      Add_Branch_Employee : 412,
      Update_Branch_Employee : 413,
      View_Branch_Employee : 414,
      Delete_Branch_Employee : 415,
   //branchmanager
      Branch_Manager_List : 421,
      Add_Branch_Manager : 422,
      Update_Branch_Manager : 423,
      View_Branch_Manager : 424,
      Delete_Branch_Manager : 425,
   //branchteam
      Branch_Team_List : 431,
      Add_Branch_Team : 432,
      Update_Branch_Team : 433,
      View_Branch_Team : 434,
      Delete_Branch_Team : 435,
   //branch Team Employee
      Branch_Team_Employee_List : 441,
      Add_Branch_Team_Employee : 442,
      Update_Branch_Team_Employee : 443,
      View_Branch_Team_Employee : 444,
      Delete_Branch_Team_Employee : 445,

   //Provider
      Provider_List : 501,
      Add_Provider : 502,
      Update_Provider : 503,
      View_Provider : 504,
      Delete_Provider : 505,
   //Provider admin
      Provider_Admin_List : 551,
      Add_Provider_Admin : 552,
      Update_Provider_Admin : 553,
      View_Provider_Admin : 554,
      Delete_Provider_Admin : 555,
   //Admission manager
      Admission_manager_List : 601,
      Add_Admission_manager : 602,
      Update_Admission_manager : 603,
      View_Admission_manager : 604,
      Delete_Admission_manager : 605,
   //Admission manager university
      Admission_manager_university_List : 651,
      Add_Admission_manager_university : 652,
      Update_Admission_manager_university : 653,
      View_Admission_manager_university : 654,
      Delete_Admission_manager_university : 655,
   //admission manager Student
      admission_manager_Student_List : 701,
      Add_admission_manager_Student : 702,
      Update_admission_manager_Student : 703,
      View_admission_manager_Student : 704,
      Delete_admission_manager_Student : 705,
   //admission manager Consultant
      admission_manager_Consultant_List : 751,
      Add_admission_manager_Consultant : 752,
      Update_admission_manager_Consultant : 753,
      View_admission_manager_Consultant : 754,
      Delete_admission_manager_Consultant : 755, 
   //admission manager Application
      admission_manager_Application_List : 801,
      Add_admission_manager_Application : 802,
      Update_admission_manager_Application : 803,
      View_admission_manager_Application : 804,
      Delete_admission_manager_Application : 805,
   
   //ake
      ake_List : 891,
      Add_ake : 892,
      Update_ake : 893,
      View_ake : 894,
      Delete_ake : 895,
   //Address
      Address_List : 901,
      Add_Address : 902,
      Update_Address : 903,
      View_Address : 904,
      Delete_Address : 905,
   //University
      University_List : 1001,
      Add_University : 1002,
      Update_University : 1003,
      View_University : 1004,
      Delete_University : 1005,
   //University type
      Universitytype_List : 1011,
      Add_Universitytype : 1012,
      Update_Universitytype : 1013,
      View_Universitytype : 1014,
      Delete_Universitytype : 1015,
   //University state
      Universitystate_List : 1021,
      Add_Universitystate : 1022,
      Update_Universitystate : 1023,
      View_Universitystate : 1024,
      Delete_Universitystate : 1025,
   //University Country
      UniversityCountry_List : 1031,
      Add_UniversityCountry : 1032,
      Update_UniversityCountry : 1033,
      View_UniversityCountry : 1034,
      Delete_UniversityCountry : 1035,
   //University Features
      UniversityFeatures_List : 1041,
      Add_UniversityFeatures : 1042,
      Update_UniversityFeatures : 1043,
      View_UniversityFeatures : 1044,
      Delete_UniversityFeatures : 1045,
   //University gallery
      Universitygallery_List : 1051,
      Add_Universitygallery : 1052,
      Update_Universitygallery : 1053,
      View_Universitygallery : 1054,
      Delete_Universitygallery : 1055,
   //University Campus
      UniversityCampus_List : 1061,
      Add_UniversityCampus : 1062,
      Update_UniversityCampus : 1063,
      View_UniversityCampus : 1064,
      Delete_UniversityCampus : 1065,
   //universityApplicationdocument
      universityApplicationdocument_List : 1071,
      Add_universityApplicationdocument : 1072,
      Update_universityApplicationdocument : 1073,
      View_universityApplicationdocument : 1074,
      Delete_universityApplicationdocument : 1075,
   //Financialinfo
      Financialinfo_List : 1081,
      Add_Financialinfo : 1082,
      Update_Financialinfo : 1083,
      View_Financialinfo : 1084,
      Delete_Financialinfo : 1085,
   //campusgallery
      campusgallery_List : 1091,
      Add_campusgallery : 1092,
      Update_campusgallery : 1093,
      View_campusgallery : 1094,
      Delete_campusgallery : 1095,
   //University Template Document
      University_Template_Document_List : 1101,
      Add_University_Template_Document : 1102,
      Update_University_Template_Document : 1103,
      View_University_Template_Document : 1104,
      Delete_University_Template_Document : 1105,
   //university campus subject
      university_campus_subject_List : 1201,
      Add_university_campus_subject : 1202,
      Update_university_campus_subject : 1203,
      View_university_campus_subject : 1204,
      Delete_university_campus_subject : 1205,
   //subject requirement
      subject_requirement_List : 1211,
      Add_subject_requirement : 1212,
      Update_subject_requirement : 1213,
      View_subject_requirement : 1214,
      Delete_subject_requirement : 1215,
   //subject requirement document
      subject_requirement_document_List : 1221,
      Add_subject_requirement_document : 1222,
      Update_subject_requirement_document : 1223,
      View_subject_requirement_document : 1224,
      Delete_subject_requirement_document : 1225,
   //subject intake
      subject_intake_List : 1231,
      Add_subject_intake : 1232,
      Update_subject_intake : 1233,
      View_subject_intake : 1234,
      Delete_subject_intake : 1235,
   //subject fee structure
      subject_fee_structure_List : 1241,
      Add_subject_fee_structure : 1242,
      Update_subject_fee_structure : 1243,
      View_subject_fee_structure : 1244,
      Delete_subject_fee_structure : 1245,
   //subject  
      subject_List : 1251,
      Add_subject : 1252,
      Update_subject : 1253,
      View_subject : 1254,
      Delete_subject : 1255,
   //sub department  
      sub_department_List : 1261,
      Add_sub_department : 1262,
      Update_sub_department : 1263,
      View_sub_department : 1264,
      Delete_sub_department : 1265,
   //program level 
      program_level_List : 1271,
      Add_program_level : 1272,
      Update_program_level : 1273,
      View_program_level : 1274,
      Delete_program_level : 1275,
   //department 
      department_List : 1281,
      Add_department : 1282,
      Update_department : 1283,
      View_department : 1284,
      Delete_department : 1285,
   //degree 
      degree_List : 1291,
      Add_degree : 1292,
      Update_degree : 1293,
      View_degree : 1294,
      Delete_degree : 1295,
   //Education Level 
      Education_Level_List : 1296,
      Add_Education_Level : 1297,
      Update_Education_Level : 1298,
      View_Education_Level : 1299,
      Delete_Education_Level : 1300,
   //DocumentGroup 
      Document_Group_List : 1301,
      Add_Document_Group : 1302,
      Update_Document_Group : 1303,
      View_Document_Group : 1304,
      Delete_Document_Group : 1305,
   //DocumentGroupDocument 
      Document_Group_Document_List : 1311,
      Add_Document_Group_Document : 1312,
      Update_Document_Group_Document : 1313,
      View_Document_Group_Document : 1314,
      Delete_Document_Group_Document : 1315,
   //SubjectDeliveryPattern 
      Subject_Delivery_Pattern_List : 1321,
      Add_Subject_Delivery_Pattern : 1322,
      Update_Subject_Delivery_Pattern : 1323,
      View_Subject_Delivery_Pattern : 1324,
      Delete_Subject_Delivery_Pattern : 1325,
   //Exam test type 
      Exam_test_type_List : 1401,
      Add_Exam_test_type : 1402,
      Update_Exam_test_type : 1403,
      View_Exam_test_type : 1404,
      Delete_Exam_test_type : 1405,
   //Duolingo 
      Duolingo_List : 1406,
      Add_Duolingo : 1407,
      Update_Duolingo : 1408,
      View_Duolingo : 1409,
      Delete_Duolingo : 1410,
   //FunctionalSkill 
      FunctionalSkill_List : 1411,
      Add_FunctionalSkill : 1412,
      Update_FunctionalSkill : 1413,
      View_FunctionalSkill : 1414,
      Delete_FunctionalSkill : 1415,
   //GCSE 
      GCSE_List : 1416,
      Add_GCSE : 1417,
      Update_GCSE : 1418,
      View_GCSE : 1419,
      Delete_GCSE : 1420,
   //IELTS 
      IELTS_List : 1421,
      Add_IELTS : 1422,
      Update_IELTS : 1423,
      View_IELTS : 1424,
      Delete_IELTS : 1425,
   //OTHERS 
      OTHERS_List : 1426,
      Add_OTHERS : 1427,
      Update_OTHERS : 1428,
      View_OTHERS : 1429,
      Delete_OTHERS : 1430,
   //PEARSON 
      PEARSON_List : 1431,
      Add_PEARSON : 1432,
      Update_PEARSON : 1433,
      View_PEARSON : 1434,
      Delete_PEARSON : 1435,
   //PTE 
      PTE_List : 1436,
      Add_PTE : 1437,
      Update_PTE : 1438,
      View_PTE : 1439,
      Delete_PTE : 1440,
   //TOFEL 
      TOFEL_List : 1441,
      Add_TOFEL : 1442,
      Update_TOFEL : 1443,
      View_TOFEL : 1444,
      Delete_TOFEL : 1445,

   //Document Category 
      Document_Category_List : 1501,
      Add_Document_Category : 1502,
      Update_Document_Category : 1503,
      View_Document_Category : 1504,
      Delete_Document_Category : 1505,
   //Document 
      Document_List : 1506,
      Add_Document : 1507,
      Update_Document : 1508,
      View_Document : 1509,
      Delete_Document : 1510,
   //Country 
      Country_List : 1531,
      Add_Country : 1532,
      Update_Country : 1533,
      View_Country : 1534,
      Delete_Country : 1535,
   //State 
      State_List : 1536,
      Add_State : 1537,
      Update_State : 1538,
      View_State : 1539,
      Delete_State : 1540,
   //Site Settings 
      Site_Settings_List : 1541,
      Add_Site_Settings : 1542,
      Update_Site_Settings : 1543,
      View_Site_Settings : 1544,
      Delete_Site_Settings : 1545,
   //Application 
      Application_List : 1551,
      Add_Application : 1552,
      Update_Application : 1553,
      View_Application : 1554,
      Delete_Application : 1555,
   //ELPT 
      ELPT_List : 1556,
      Add_ELPT : 1557,
      Update_ELPT : 1558,
      View_ELPT : 1559,
      Delete_ELPT : 1560,
   //Permission 
      Permission_List : 1571,
      Add_Permission : 1572,
      Update_Permission : 1573,
      View_Permission : 1574,
      Delete_Permission : 1575,
   //Nationality 
      Nationality_List : 1581,
      Add_Nationality : 1582,
      Update_Nationality : 1583,
      View_Nationality : 1584,
      Delete_Nationality : 1585,

      //CommissionGroup 
      CommissionGroup_List : 1591,
      Add_CommissionGroup : 1592,
      Update_CommissionGroup : 1593,
      View_CommissionGroup : 1594,
      Delete_CommissionGroup : 1595,
      
      //GroupPriceRange 
      GroupPriceRange_List : 1596,
      Add_GroupPriceRange : 1597,
      Update_GroupPriceRange : 1598,
      View_GroupPriceRange : 1599,
      Delete_GroupPriceRange : 1600,
      
      //ConsultantCommissionGroup 
      ConsultantCommissionGroup_List : 1601,
      Add_ConsultantCommissionGroup : 1602,
      Update_ConsultantCommissionGroup : 1603,
      View_ConsultantCommissionGroup : 1604,
      Delete_ConsultantCommissionGroup : 1605,

      Consultant_type_List : 117,
      View_Consultant_type : 118,
      Edit_Consultant_type: 119,
      Delete_Consultant_type: 120,

      AccountIntake_List :1611,
      Add_AccountIntake: 1612,
      Update_AccountIntake: 1613,
      View_AccountIntake: 1614,
      Delete_AccountIntake: 1615,



};
